export const rooms = [
  { name: 'Hotel Nile View', location: 'Cairo, Egypt', image: "../../../../assets/images/New folder (2)/pic (1).png" },
  { name: 'The Royal Pyramid', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (2).png' },
  { name: 'Desert Sands Resort', location: 'Luxor, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (4).png' },
  { name: 'Red Sea Breeze', location: 'Hurghada, Egypt', image: "../.../../../../../assets/images/New folder (2)/pic (7).png"},
  { name: 'Oasis Hotel', location: 'Alexandria, Egypt', image: "../.../../../../../assets/images/New folder (2)/pic (8).png" },
  { name: "Pharaoh's Palace", location: 'Cairo, Egypt', image: "../../../../assets/images/New folder (2)/pic (9).png" },
  { name: 'Temple View Hotel', location: 'Aswan, Egypt', image: '../../../../assets/images/New folder (2)/pic (10).png' },
  { name: 'Sphinx Suites', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (12).png' },
  { name: 'Blue Nile Inn', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (13).png' },
  { name: 'Mediterranean Breeze', location: 'Alexandria, Egypt', image: '../.../../../../../assets/images/New folder (14)/pic.png' },
  { name: 'Luxor Grand Hotel', location: 'Luxor, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (15).png' },
  { name: 'Sharm Paradise Resort', location: 'Sharm El-Sheikh, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (16).png' },
  { name: 'Cairo Sunset Hotel', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (17).png' },
  { name: 'Ancient Sands Resort', location: 'Hurghada, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (18).png' },
  { name: 'Pyramid Peak Inn', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (19).png' },
  { name: 'The Nile Palace', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (1).png' },
  { name: 'Horizon Nile View', location: 'Aswan, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (2).png' },
  { name: 'The Alexandria Inn', location: 'Alexandria, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (4).png' },
  { name: 'Golden Sands Hotel', location: 'Hurghada, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (7).png' },
  { name: 'Cairo Sky Suites', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (8).png' },
  { name: 'Sahara Oasis Resort', location: 'Luxor, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (9).png' },
  { name: 'The Royal Pharaoh', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (10).png' },
  { name: 'The Blue Pyramid', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (12).png' },
  { name: 'Tahrir Square Hotel', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (13).png' },
  { name: 'Golden Nile Suites', location: 'Aswan, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (14).png' },
  { name: 'Mediterranean Sands Resort', location: 'Alexandria, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (15).png' },
  { name: 'Sharm Blue Bay', location: 'Sharm El-Sheikh, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (16).png' },
  { name: 'Luxor Horizon', location: 'Luxor, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (17).png' },
  { name: 'Pyramid Valley Resort', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (19).png' },
  { name: 'Red Sea Horizon', location: 'Hurghada, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (2).png' },
  { name: 'The Grand Nile', location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (1).png' },
  { name: 'Temple Sands Hotel', location: 'Aswan, Egypt', image: '../.../../../../../assets/images/New folder (4)/pic (2).png' },
  { name: 'The Mediterranean Pearl', location: 'Alexandria, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (10).png' },
  { name: 'Giza Heights Resort', location: 'Giza, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (12).png' },
  { name: "The Pharaoh's Retreat", location: 'Cairo, Egypt', image: '../.../../../../../assets/images/New folder (2)/pic (15).png' },
  // { name: 'Aswan Sky Suites', location: 'Aswan, Egypt', image: 'https://example.com/images/aswan-sky-suites.jpg' },
  // { name: 'Luxor Temple Resort', location: 'Luxor, Egypt', image: 'https://example.com/images/luxor-temple-resort.jpg' },
  // { name: 'Blue Lagoon Resort', location: 'Hurghada, Egypt', image: 'https://example.com/images/blue-lagoon-resort.jpg' },
  // { name: 'The Sphinx View', location: 'Giza, Egypt', image: 'https://example.com/images/the-sphinx-view.jpg' },
  // { name: 'Sunset Sands Resort', location: 'Sharm El-Sheikh, Egypt', image: 'https://example.com/images/sunset-sands-resort.jpg' },
  // { name: 'The Cairo Crown', location: 'Cairo, Egypt', image: 'https://example.com/images/the-cairo-crown.jpg' },
  // { name: 'Palm Oasis Hotel', location: 'Sharm El-Sheikh, Egypt', image: 'https://example.com/images/palm-oasis-hotel.jpg' },
  // { name: 'The Nile Jewel', location: 'Aswan, Egypt', image: 'https://example.com/images/the-nile-jewel.jpg' },
  // { name: 'The Pyramid Resort', location: 'Giza, Egypt', image: 'https://example.com/images/the-pyramid-resort.jpg' },
  // { name: 'Cairo Golden Plaza', location: 'Cairo, Egypt', image: 'https://example.com/images/cairo-golden-plaza.jpg' },
  // { name: 'Alexandria Harbor Resort', location: 'Alexandria, Egypt', image: 'https://example.com/images/alexandria-harbor-resort.jpg' },
];
